### ISSUE TITLE
Read me 

### ISSUE THREAD

**Issue by kevinnjagi44** [gr8401/OCT---Transferlearning#1]
Can you please update the Readme due to the changes you added.any language will be appreciated

**Comment by kevinnjagi44** [comment]
Can i contact any of the contributors personally.My email is murimikevo@gmail.com

**Comment by kevinnjagi44** [comment]
@Daniel_Ramsing can i contact you

**Comment by DanielRLund** [comment]
This project is mainly used as a personal repository for a project we're conducting at the university, as such there is no real professionalism to the repo-updates or commits.

I can update the ReadME file, but it might take a while before I get around to it.

Are there any specific areas you are interested in knowing more about?
